### ISSUE TITLE
Rnbo 1.3.3 errors

### ISSUE THREAD

**Issue by Tomavatars** [Cycling74/RNBOMetasound#54]
When updating RNBO to 1.3.3 and exporting patches, I got these issues

![CleanShot 2024-11-06 at 12 49 36](https://github.com/user-attachments/assets/ad57a6dc-3f16-4e04-9df9-f9dd0f0b225f)
![CleanShot 2024-11-06 at 12 42 39](https://github.com/user-attachments/assets/afbf1530-0bbc-4094-8483-d32d608a7259)

**Comment by jinpavg** [comment]
Hi @Tomavatars , I can use 1.3.3 without issue -- I wonder, though, if perhaps you exported some of your patches with 1.3.2 and some with 1.3.3? This can cause some issues. There are two ways you can try to address this:

1. Look through your exported patcher directories, you can remove all instances of this `rnbo/` directory except for the latest one that you've exported.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/9c6e8ebc-1b2b-4e33-94a9-29f46ec96bb1">

2. Re-export all patchers with 1.3.3 (or whatever is the latest version), so that all instances of this `rnbo/` library are the same. 

This issue is currently tracked on #30, and we want to improve this experience, but these are the suggested workarounds for now.

**Comment by Tomavatars** [comment]
Thanks. 
I made this, re exported everything with 1.3.3
I might try again by deleting all my export folders, but that takes time!
